version: "3.8"

# Configuración para Linux con MongoDB local
# MongoDB se ejecuta en el host (servidor) no en contenedor
# Los contenedores se conectan a MongoDB usando la IP del gateway de Docker (172.17.0.1)
# Servicios: API Node.js + Redis (MongoDB local)

services:
  # API Node.js
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: privaap-api
    restart: unless-stopped
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - PORT=3004
      - MONGODB_URI=mongodb://privaap_admin:privaap123@172.17.0.1:27017/privaap?authSource=admin
      - JWT_SECRET=your_jwt_secret_here_change_in_production
      - CLOUDINARY_CLOUD_NAME=your_cloudinary_name
      - CLOUDINARY_API_KEY=your_cloudinary_api_key
      - CLOUDINARY_API_SECRET=your_cloudinary_api_secret
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=your_email@gmail.com
      - SMTP_PASS=your_app_password
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    # MongoDB local - no depende de contenedor
    networks:
      - privaap-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis (opcional, para cache y rate limiting)
  redis:
    image: redis:7-alpine
    container_name: privaap-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - privaap-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local

networks:
  privaap-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
